( CASE WHEN (SELECT COALESCE(SUM(round((RIP.UNITBASEPRICE*(RIP.DISCOUNTPERC)/100*RIP.QTY),2)),0) 
FROM T_SVC_RO_MSTR SRM 
INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID 
INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID 
INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID =PM.PARTID 
INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID 
WHERE RIP.CHARGETYPECODE IN ('SO-FLEKSIB','SO-INS','SO-W','SO-INT') 
AND RIM.ROINVID = ROINV.ROINVID) > 0 
OR (SELECT COALESCE(SUM(RIP.DISCOUNTRM),0) 
FROM T_SVC_RO_MSTR SRM 
INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID 
INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID 
INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID =PM.PARTID 
INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID 
WHERE RIP.CHARGETYPECODE IN ('SO-FLEKSIB','SO-INS','SO-W','SO-INT') 
AND RIM.ROINVID = ROINV.ROINVID) > 0 
OR (SELECT COALESCE(SUM(ROOP.DISCOUNTBPRICE*ROOP.DISCOUNTPERC/100),0) 
FROM T_SVC_RO_INV_MSTR RIM 
INNER JOIN T_SVC_RO_INV_OP ROOP ON RIM.ROINVID = ROOP.ROINVID 
WHERE RIM.ROINVID = ROINV.ROINVID 
AND RIM.ROINVTYPECODE IN ('SOFLEKSIB','SOINT')) > 0 
THEN 0 ELSE NVL(ROINV.OTHERDISC,0) END 
)AS CAMPDISC ,