
    SELECT OM.OUTLETCODE, OM.OUTLETNAME, PRM.CUSTID, CASE WHEN PRM.PAYTYPECODE = 'INS' THEN PRM.CUSTNO ELSE CP.CUSTNO END AS CUSTNO, PRM.CUSTNAME, PRM.REGNO, (SELECT CD.DETAILDESCRIPTION
        FROM T_PI_CODE_MSTR CM INNER JOIN T_PI_CODE_DTL CD ON CM.HEADERCODEID = CD.HEADERCODEID
        WHERE CM.HEADERCODE = 'PAYTYPE' AND CM.STATUS = 'A' AND CD.RECSTATUS = 1 AND CD.DETAILVALUE = PRM.PAYTYPECODE) AS PAYTYPECODE, PRM.PRID, PRM.PRNO, PRM.PRDATE, PRM.TOTALPMTAMT, NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND
            PDA.PAYMODECODE = 'CASH'),'0.00') AS CASHAMT, NVL((SELECT SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND PDB.PAYMODECODE in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') AS CCAMT, NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID =
PRM.PRID AND PDC.PAYMODECODE not in ('CASH') AND PDC.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') AS OTHAMT, NVL((SELECT SUM(PDD.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDD
        WHERE PDD.PRID = PRM.PRID AND PDD.PAYMODECODE LIKE '%VOUCHER%'),'0.00') AS VOUCHERAMT, (SELECT
            LISTAGG(DOCNO, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 and SPD.DOCTYPE IN ('CRO','RO')) AS CRONO, (SELECT LISTAGG(DEPBALANCE, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1) AS CRODEP, NULL AS APPLIEDAMT, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE = 'CASH' ),'0.00') as TOTALAPPLIEDAMTCASH, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND
            PDA.PAYMODECODE in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTCREDITCARD, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE not in ('CASH') AND
            PDA.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTOTH, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE LIKE '%VOUCHER%'),'0.00')
as TOTALAPPLIEDAMTVOUCHER, NVL((SELECT SUM(NVL(ROINV.TTLEVAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD INNER JOIN T_SVC_RO_MSTR ROMSTR ON ROMSTR.ROID = SPD.DOCID INNER JOIN T_SVC_RO_INV_MSTR ROINV ON ROMSTR.ROID = ROINV.ROID
        WHERE SPD.DEPBALANCE IS NOT NULL and SPD.recstatus = 1 AND ROMSTR.CUSTPROFILEID = CP.CUSTPROFILEID),'0.00') AS TOTALEVOUCHER, NVL((SELECT SUM(NVL(EM.EVVALUE, '0.00' ))
        FROM T_CMS_EVOUCHER_MSTR EM INNER JOIN T_VEHCUSTPROFILE VCP ON VCP.VCPROFILEID = EM.VCPROFILEID AND VCP.RECSTATUS = 1
        WHERE
VCP.CUSTPROFILEID=CP.CUSTPROFILEID AND EM.EXPIRYDATE > SYSDATE -1 AND EM.STATUS='N'),'0.00') AS BALANCEEVOUCHER, NVL(PRM.WRITEOFFAMT,'0.00') AS WRITEOFF, NVL( NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND PDA.PAYMODECODE = 'CASH'),'0.00') - NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE = 'CASH' ),'0.00'),'0.00')as BALCASHAMT, NVL( NVL((SELECT SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND PDB.PAYMODECODE in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') - NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE in (SELECT
                PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALCCAMT, NVL( NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID = PRM.PRID AND PDC.PAYMODECODE not in ('CASH') AND PDC.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE
PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') - NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE not in ('CASH') AND PDA.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND
                PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALOTHAMT, NVL((SELECT SUM(NVL(VMSTR.VOUCHERAMT, '0.00' ))
        FROM T_SVC_VOUCHER_MSTR VMSTR INNER JOIN T_SVC_VOUCHER_DTL VDTL ON VMSTR.VOUCHERID = VDTL.VOUCHERID
        WHERE VDTL.STATUS = 'V' AND VMSTR.VALIDITYSDATE < SYSDATE AND (VMSTR.VALIDITYEDATE IS NULL OR VMSTR.VALIDITYEDATE > SYSDATE +1) AND PRM.REGNO = VDTL.REGNO ),'0.00')
AS BALVOUCHER
    FROM T_SVC_PMTRECEIPT_MSTR PRM INNER JOIN T_OUTLET_MSTR OM ON PRM.OUTLETID = OM.OUTLETID LEFT JOIN T_CUSTPROFILE CP ON PRM.CUSTID = CP.CUSTID
    WHERE OM.RECSTATUS = 1 AND PRM.PAYTYPECODE <> 'CN' AND PRM.STATUS = 'O' AND OM.OUTLETTYPE = 'BRANCH'AND OM.OUTLETCODE = :PARAMOUTLETCODE AND PRM.Prdate < TO_DATE('07/12/2020','DD/MM/YYYY') + 1 AND PRM.PAYTYPECODE IN ('CC','CHQ','DEP','INS','NOR','OD')
UNION
    SELECT OM.OUTLETCODE, OM.OUTLETNAME, PRM.CUSTID, CASE WHEN PRM.PAYTYPECODE = 'INS' THEN PRM.CUSTNO ELSE CP.CUSTNO END AS CUSTNO, PRM.CUSTNAME,
        PRM.REGNO, (SELECT CD.DETAILDESCRIPTION
        FROM T_PI_CODE_MSTR CM INNER JOIN T_PI_CODE_DTL CD ON CM.HEADERCODEID = CD.HEADERCODEID
        WHERE CM.HEADERCODE = 'PAYTYPE' AND CM.STATUS = 'A' AND CD.RECSTATUS = 1 AND CD.DETAILVALUE = PRM.PAYTYPECODE) AS PAYTYPECODE, PRM.PRID, PRM.PRNO, PRM.PRDATE, PRM.TOTALPMTAMT, NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND PDA.PAYMODECODE = 'CASH'),'0.00') AS CASHAMT, NVL((SELECT SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND
            PDB.PAYMODECODE in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') AS CCAMT, NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID = PRM.PRID AND PDC.PAYMODECODE not in ('CASH') AND PDC.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') AS OTHAMT, NVL((SELECT SUM(PDD.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDD
        WHERE PDD.PRID = PRM.PRID AND PDD.PAYMODECODE LIKE '%VOUCHER%'),'0.00') AS VOUCHERAMT, (SELECT LISTAGG(DOCNO, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 and SPD.DOCTYPE IN ('CRO','RO')) CRONO, (SELECT LISTAGG(DEPBALANCE, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1) CRODEP, (SELECT LISTAGG(TO_CHAR((SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' )), '9,990.99'), '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1) APPLIEDAMT, NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE='CASH' AND SPD.DOCFLAG = 'APPLY'),'0.00') as TOTALAPPLIEDAMTCASH, NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID =
SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTCREDITCARD, NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID =
SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE not in ('CASH') AND SPD.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTOTH, NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID =
SPD.PRID and recstatus = 1 AND SPD.DOCFLAG = 'APPLY' AND SPD.PAYMODECODE LIKE '%VOUCHER%'),'0.00') as TOTALAPPLIEDAMTVOUCHER, NVL((SELECT SUM(NVL(ROINV.TTLEVAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD INNER JOIN T_SVC_RO_MSTR ROMSTR ON ROMSTR.ROID = SPD.DOCID INNER JOIN T_SVC_RO_INV_MSTR ROINV ON ROMSTR.ROID = ROINV.ROID
        WHERE SPD.DEPBALANCE IS NOT NULL and SPD.recstatus = 1 AND ROMSTR.CUSTPROFILEID = CP.CUSTPROFILEID),'0.00') AS TOTALEVOUCHER, NVL((SELECT SUM(NVL(EM.EVVALUE, '0.00' ))
        FROM T_CMS_EVOUCHER_MSTR EM INNER JOIN T_VEHCUSTPROFILE VCP
            ON VCP.VCPROFILEID = EM.VCPROFILEID AND VCP.RECSTATUS = 1
        WHERE VCP.CUSTPROFILEID=CP.CUSTPROFILEID AND EM.EXPIRYDATE > SYSDATE -1 AND EM.STATUS='N'),'0.00') AS BALANCEEVOUCHER, NVL(PRM.WRITEOFFAMT,'0.00') AS WRITEOFF, NVL( NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND PDA.PAYMODECODE = 'CASH'),'0.00') - NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE='CASH' AND SPD.DOCFLAG =
'APPLY'),'0.00'),'0.00')as BALCASHAMT, NVL( NVL((SELECT SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND PDB.PAYMODECODE in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') - NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALCCAMT, NVL( NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID = PRM.PRID AND PDC.PAYMODECODE
not in ('CASH') AND PDC.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00') - NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID = SPD.PRID and recstatus = 1 AND
            SPD.PAYMODECODE not in ('CASH') AND SPD.PAYMODECODE not in (SELECT PAYM.PAYMENTMODECODE
            FROM T_PAYMENTMODE PAYM
            WHERE PAYM.RECSTATUS = 1 AND PAYM.EFFSTARTDATE < CURRENT_DATE AND (PAYM.EFFENDDATE > CURRENT_DATE-1 OR PAYM.EFFENDDATE IS NULL) AND PAYM.BIZUNITCODE = 'AFTERSALES' AND CREDITCARDFLAG = 'Y' AND PAYM.PAYMENTMODECODE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALOTHAMT, NVL((SELECT SUM(NVL(VMSTR.VOUCHERAMT, '0.00' ))
        FROM T_SVC_VOUCHER_MSTR VMSTR INNER JOIN T_SVC_VOUCHER_DTL VDTL ON VMSTR.VOUCHERID = VDTL.VOUCHERID
        WHERE
VDTL.STATUS = 'V' AND VMSTR.VALIDITYSDATE < SYSDATE AND (VMSTR.VALIDITYEDATE IS NULL OR VMSTR.VALIDITYEDATE > SYSDATE +1) AND PRM.REGNO = VDTL.REGNO ),'0.00') AS BALVOUCHER
    FROM T_SVC_PMTRECEIPT_MSTR PRM INNER JOIN T_OUTLET_MSTR OM ON PRM.OUTLETID = OM.OUTLETID LEFT JOIN T_CUSTPROFILE CP ON PRM.CUSTID = CP.CUSTID
    WHERE OM.RECSTATUS = 1 AND PRM.PAYTYPECODE <> 'CN' AND PRM.STATUS = 'L' AND PRM.PRID in ( SELECT PRID
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DEPBALANCE > 0 and recstatus = 1) AND OM.OUTLETTYPE = 'BRANCH'AND
        PRM.OUTLETCODE = :PARAMOUTLETCODE AND PRM.Prdate < TO_DATE('07/12/2020','DD/MM/YYYY') + 1 AND PRM.PAYTYPECODE IN ('CC','CHQ','DEP','INS','NOR','OD''CC','CHQ','DEP','INS','NOR','OD')
UNION
    SELECT OM.OUTLETCODE, OM.OUTLETNAME, PRM.CUSTID, CASE WHEN PRM.PAYTYPECODE = 'INS' THEN PRM.CUSTNO ELSE CP.CUSTNO END AS CUSTNO, PRM.CUSTNAME, PRM.REGNO, (SELECT CD.DETAILDESCRIPTION
        FROM T_PI_CODE_MSTR CM INNER JOIN T_PI_CODE_DTL CD ON CM.HEADERCODEID = CD.HEADERCODEID
        WHERE CM.HEADERCODE = 'PAYTYPE' AND CM.STATUS = 'A' AND CD.RECSTATUS = 1 AND CD.DETAILVALUE = PRM.PAYTYPECODE)
AS PAYTYPECODE, PRM.PRID, PRM.PRNO, PRM.PRDATE, PRM.TOTALPMTAMT, NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND PDA.PAYMODECODE = 'CASH'),'0.00') AS CASHAMT, NVL((SELECT SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND PDB.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR
                CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') AS CCAMT, NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID = PRM.PRID AND PDC.PAYMODECODE not in ('CASH') AND PDC.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%')
                AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') AS OTHAMT, NVL((SELECT SUM(PDD.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDD
        WHERE PDD.PRID = PRM.PRID AND PDD.PAYMODECODE LIKE '%VOUCHER%'),'0.00') AS VOUCHERAMT, (SELECT LISTAGG(DOCNO, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 and SPD.DOCTYPE IN ('CRO','RO')) AS CRONO, (SELECT LISTAGG(DEPBALANCE, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1) AS CRODEP, NULL AS APPLIEDAMT, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE = 'CASH' ),'0.00') as TOTALAPPLIEDAMTCASH, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND
            PDA.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTCREDITCARD, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND
            PDA.PAYMODECODE not in ('CASH') AND PDA.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTOTH, NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND
            PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE LIKE '%VOUCHER%'),'0.00') as TOTALAPPLIEDAMTVOUCHER, NVL((SELECT SUM(NVL(ROINV.TTLEVAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD INNER JOIN T_SVC_RO_MSTR ROMSTR ON ROMSTR.ROID = SPD.DOCID INNER JOIN T_SVC_RO_INV_MSTR ROINV ON ROMSTR.ROID = ROINV.ROID
        WHERE SPD.DEPBALANCE IS NOT NULL and SPD.recstatus = 1 AND ROMSTR.CUSTPROFILEID = CP.CUSTPROFILEID),'0.00') AS TOTALEVOUCHER, NVL((SELECT SUM(NVL(EM.EVVALUE, '0.00' ))
        FROM T_CMS_EVOUCHER_MSTR EM INNER JOIN T_VEHCUSTPROFILE VCP ON VCP.VCPROFILEID =
EM.VCPROFILEID AND VCP.RECSTATUS = 1
        WHERE VCP.CUSTPROFILEID=CP.CUSTPROFILEID AND EM.EXPIRYDATE > SYSDATE -1 AND EM.STATUS='N'),'0.00') AS BALANCEEVOUCHER, NVL(PRM.WRITEOFFAMT,'0.00') AS WRITEOFF, NVL( NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND PDA.PAYMODECODE = 'CASH'),'0.00') - NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE = 'CASH' ),'0.00'),'0.00')as BALCASHAMT, NVL( NVL((SELECT
            SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND PDB.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') - NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID
= PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALCCAMT, NVL( NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID = PRM.PRID AND PDC.PAYMODECODE not in ('CASH') AND
            PDC.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') - NVL((SELECT SUM(NVL(PDA.TOPAYAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO PDA
        WHERE PDA.RECSTATUS= 1 AND PDA.PRID = PRM.PRID AND PDA.DOCFLAG = 'APPLY' AND PDA.PAYMODECODE not in ('CASH') AND
            PDA.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALOTHAMT, NVL((SELECT SUM(NVL(VMSTR.VOUCHERAMT, '0.00' ))
        FROM T_SVC_VOUCHER_MSTR VMSTR INNER JOIN T_SVC_VOUCHER_DTL VDTL ON VMSTR.VOUCHERID = VDTL.VOUCHERID
        WHERE VDTL.STATUS =
'V' AND VMSTR.VALIDITYSDATE < SYSDATE AND (VMSTR.VALIDITYEDATE IS NULL OR VMSTR.VALIDITYEDATE > SYSDATE +1) AND PRM.REGNO = VDTL.REGNO ),'0.00') AS BALVOUCHER
    FROM T_SVC_PMTRECEIPT_MSTR PRM INNER JOIN T_OUTLET_MSTR OM ON PRM.OUTLETID = OM.OUTLETID LEFT JOIN T_CUSTPROFILE CP ON PRM.CUSTID = CP.CUSTID
    WHERE OM.RECSTATUS = 1 AND PRM.PAYTYPECODE <> 'CN' AND PRM.STATUS = 'O' AND OM.OUTLETTYPE != 'BRANCH'AND OM.OUTLETCODE = :PARAMOUTLETCODE AND PRM.Prdate < TO_DATE('07/12/2020','DD/MM/YYYY') + 1 AND PRM.PAYTYPECODE IN
('CC','CHQ','DEP','INS','NOR','OD''CC','CHQ','DEP','INS','NOR','OD''CC','CHQ','DEP','INS','NOR','OD')
UNION
    SELECT OM.OUTLETCODE, OM.OUTLETNAME, PRM.CUSTID, CASE WHEN PRM.PAYTYPECODE = 'INS' THEN PRM.CUSTNO ELSE CP.CUSTNO END AS CUSTNO, PRM.CUSTNAME, PRM.REGNO, (SELECT CD.DETAILDESCRIPTION
        FROM T_PI_CODE_MSTR CM INNER JOIN T_PI_CODE_DTL CD ON CM.HEADERCODEID = CD.HEADERCODEID
        WHERE CM.HEADERCODE = 'PAYTYPE' AND CM.STATUS = 'A' AND CD.RECSTATUS = 1 AND CD.DETAILVALUE = PRM.PAYTYPECODE) AS PAYTYPECODE, PRM.PRID, PRM.PRNO, PRM.PRDATE, PRM.TOTALPMTAMT,
        NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND PDA.PAYMODECODE = 'CASH'),'0.00') AS CASHAMT, NVL((SELECT SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND PDB.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND
                CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') AS CCAMT, NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID = PRM.PRID AND PDC.PAYMODECODE not in ('CASH') AND PDC.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') AS OTHAMT,
        NVL((SELECT SUM(PDD.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDD
        WHERE PDD.PRID = PRM.PRID AND PDD.PAYMODECODE LIKE '%VOUCHER%'),'0.00') AS VOUCHERAMT, (SELECT LISTAGG(DOCNO, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 and SPD.DOCTYPE IN ('CRO','RO')) CRONO, (SELECT LISTAGG(DEPBALANCE, '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1) CRODEP, (SELECT LISTAGG(TO_CHAR((SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' )), '9,990.99'), '
') WITHIN GROUP (ORDER BY DOCNO DESC)
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.DOCFLAG = 'APPLY') APPLIEDAMT, NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE='CASH' AND SPD.DOCFLAG = 'APPLY'),'0.00') as TOTALAPPLIEDAMTCASH, NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND PRM.PRID =
SPD.PRID AND SPD.DOCFLAG = 'APPLY' and recstatus = 1 AND SPD.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTCREDITCARD, NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE
SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE not in ('CASH') AND SPD.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') as TOTALAPPLIEDAMTOTH, NVL((SELECT SUM(NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE LIKE '%VOUCHER%'),'0.00') as TOTALAPPLIEDAMTVOUCHER, NVL((SELECT SUM(NVL(ROINV.TTLEVAMT, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD INNER JOIN T_SVC_RO_MSTR ROMSTR ON ROMSTR.ROID = SPD.DOCID INNER JOIN T_SVC_RO_INV_MSTR ROINV ON ROMSTR.ROID = ROINV.ROID
        WHERE SPD.DEPBALANCE IS NOT NULL and SPD.recstatus = 1 AND ROMSTR.CUSTPROFILEID = CP.CUSTPROFILEID),'0.00') AS TOTALEVOUCHER,
        NVL((SELECT SUM(NVL(EM.EVVALUE, '0.00' ))
        FROM T_CMS_EVOUCHER_MSTR EM INNER JOIN T_VEHCUSTPROFILE VCP ON VCP.VCPROFILEID = EM.VCPROFILEID AND VCP.RECSTATUS = 1
        WHERE VCP.CUSTPROFILEID=CP.CUSTPROFILEID AND EM.EXPIRYDATE > SYSDATE -1 AND EM.STATUS='N'),'0.00') AS BALANCEEVOUCHER, NVL(PRM.WRITEOFFAMT,'0.00') AS WRITEOFF, NVL( NVL((SELECT SUM(PDA.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDA
        WHERE PDA.PRID = PRM.PRID AND PDA.PAYMODECODE = 'CASH'),'0.00') - NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE
SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE='CASH'),'0.00'),'0.00')as BALCASHAMT, NVL( NVL((SELECT SUM(PDB.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDB
        WHERE PDB.PRID = PRM.PRID AND PDB.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND
                CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') - NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND
                CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALCCAMT, NVL( NVL((SELECT SUM(PDC.PMTAMT)
        FROM T_SVC_PMTRECEIPT_DTL PDC
        WHERE PDC.PRID = PRM.PRID AND PDC.PAYMODECODE not in ('CASH') AND PDC.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00') -
NVL((SELECT SUM(SPD.TOPAYAMT-NVL(SPD.DEPBALANCE, '0.00' ))
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DOCFLAG = 'APPLY' AND PRM.PRID = SPD.PRID and recstatus = 1 AND SPD.PAYMODECODE not in ('CASH') AND SPD.PAYMODECODE not in (SELECT CD.DETAILVALUE
            FROM T_PI_CODE_DTL CD
            WHERE CD.HEADERCODEID = ( SELECT CM.HEADERCODEID
                FROM T_PI_CODE_MSTR CM
                WHERE CM.HEADERCODE = 'PAYMODE' AND CM.STATUS = 'A') AND CD.RECSTATUS = 1 AND (CD.DETAILVALUE LIKE '%CARD%' OR CD.DETAILVALUE LIKE '%CC%'OR CD.DETAILVALUE LIKE '%CRD%') AND
                CD.DETAILVALUE NOT LIKE '%VOUCHER%')),'0.00'),'0.00')as BALOTHAMT, NVL((SELECT SUM(NVL(VMSTR.VOUCHERAMT, '0.00' ))
        FROM T_SVC_VOUCHER_MSTR VMSTR INNER JOIN T_SVC_VOUCHER_DTL VDTL ON VMSTR.VOUCHERID = VDTL.VOUCHERID
        WHERE VDTL.STATUS = 'V' AND VMSTR.VALIDITYSDATE < SYSDATE AND (VMSTR.VALIDITYEDATE IS NULL OR VMSTR.VALIDITYEDATE > SYSDATE +1) AND PRM.REGNO = VDTL.REGNO ),'0.00') AS BALVOUCHER
    FROM T_SVC_PMTRECEIPT_MSTR PRM INNER JOIN T_OUTLET_MSTR OM ON PRM.OUTLETID = OM.OUTLETID LEFT JOIN T_CUSTPROFILE CP ON PRM.CUSTID = CP.CUSTID
    WHERE
OM.RECSTATUS = 1 AND PRM.PAYTYPECODE <> 'CN' AND PRM.STATUS = 'L' AND PRM.PRID in ( SELECT PRID
        FROM T_SVC_PMTRECEIPT_DTL_INFO SPD
        WHERE SPD.RECSTATUS= 1 AND SPD.DEPBALANCE > 0 and recstatus = 1) AND OM.OUTLETTYPE != 'BRANCH'AND PRM.OUTLETCODE = :PARAMOUTLETCODE AND PRM.Prdate < TO_DATE('07/12/2020','DD/MM/YYYY') + 1 AND PRM.PAYTYPECODE IN ('CC','CHQ','DEP','INS','NOR','OD''CC','CHQ','DEP','INS','NOR','OD''CC','CHQ','DEP','INS','NOR','OD''CC','CHQ','DEP','INS','NOR','OD')
ORDER by CUSTNAME, PRNO