SELECT NVL(PGDB.GSTAMTWRND, 0) AS GSTAMTWRND, NVL(PGDB.AMTWGSTWRND, 0) AS AMTWGSTWRND, PGM.GINNO, PGM.GINDATE, PGDB.PONO, PGM.CANCELREMARKS, PGM.DOCNO, PGM.CREATEDBY, PGM.DOCTYPE, PGDB.SUPPLYPARTNO, PGDB.BINLOTCODE, NVL(PGDB.UNITAVGCOST, 0) AS UNITAVGCOST, NVL(PGDB.UNITPOISCOST, 0) AS UNITPOISCOST, NVL(PGDB.TOTALAVGCOST, 0) AS TOTALAVGCOST, NVL(PGDB.TOTALPOISCOSTWOGST, 0) AS TOTALPOISCOSTWOGST, NVL(PGDB.QTYRCVD, 0) AS QTYRCVD,
    PPM.PARTDESC, PPM.REMARKS, POM.SUPPLIERCODE, POM.UPDATEDBY, POM.PODATE, POM.ORDERTYPEID, ( 	SELECT ORDMSTR.ORDERTYPECODE
    FROM T_PI_ORDERTYPE_MSTR ORDMSTR
    WHERE 		ORDMSTR.ORDERTYPEID = POM.ORDERTYPEID ) AS ORDERTYPECODE, ( 	SELECT OM.OUTLETTYPE
    FROM T_OUTLET_MSTR OM
    WHERE 		OM.OUTLETCODE = PGM.OUTLETCODE ) AS OUTLETTYPE, ( 	SELECT PDM.DONO
    FROM T_PI_DO_MSTR PDM
    WHERE 		PGM.DOCID = PDM.DOID ) AS DONO, PGDB.PARTID, PGDB.POID,
    NVL(PGDB.GSTTAXAMT, 0) AS GSTTAXAMT, NVL(PGDB.TOTALPOISCOSTWGST, 0) AS TOTALPOISCOSTWGST, ( 	SELECT SM.SUPPLIERNAME
    FROM T_PI_SUPPLIER_MSTR SM
    WHERE 		SM.SUPPLIERID = POM.SUPPLIERID ) AS SUPPLIERNAME, PGM.OUTLETCODE, ( 	SELECT OM.OUTLETNAME
    FROM T_OUTLET_MSTR OM
    WHERE 		OM.OUTLETID = PGM.OUTLETID ) AS OUTLETNAME, PGM.TAXMETHOD, (SELECT UOMMSTR.UOMCODE AS UOMCODE
    FROM T_PI_PO_DTL PODTL INNER JOIN T_PI_UOM_MSTR UOMMSTR ON PODTL.UOMID =
UOMMSTR.UOMID
    WHERE PODTL.PARTID = PPM.PARTID AND PODTL.POID = POM.POID AND ROWNUM = 1) AS UOMCODE
FROM T_PI_GIN_MSTR	 PGM INNER JOIN T_PI_GIN_DTL_BIN PGDB ON PGM.GINID = PGDB.GINID INNER JOIN T_PI_PART_MSTR	 PPM ON PGDB.SUPPLYPARTID = PPM.PARTID INNER JOIN T_PI_PO_MSTR	 POM ON PGDB.POID = POM.POID
WHERE PGM.STATUS = 'V' AND PGM.OUTLETCODE = :PARAMOUTLETCODE AND PGM.GINDATE >= TO_DATE('01/12/2020','DD/MM/YYYY') AND PGM.GINDATE < TO_DATE('31/12/2020','DD/MM/
YYYY') + 1
ORDER BY PGM.GINNO