    SELECT ROM.OUTLETID, ROM.REGNO, VEHVAR.MVARIANTDESC, ROM.STATUS, SAM.STAFFID, SAM.SVCADVISORNAME, PVR.REMARKS AS REMARKS, CASE WHEN ROM.RONO IS NOT NULL THEN
ROM.RONO ELSE PRE.SUPNO END AS RONO, CASE WHEN ROM.RODATE IS NOT NULL THEN ROM.RODATE ELSE PRE.supdate END AS RODATE, ROM.ARRIVALTIME AS ARRIVALDATE,
        TRUNC(SYSDATE) - TRUNC(ROM.ARRIVALTIME) AS PENDINGDAYS, ((((86400*(TRUNC(current_timestamp)-TRUNC(ROM.RODATE)))/60)/60)/24) AS PENDINGRODAYS, PD.DETAILDESCRIPTION AS ROTYPE,
        ((SELECT COALESCE(SUM(CASE WHEN PART.CHARGETYPECODE = 'SO-W' THEN (PART.DISCOUNTUNITPRICE * PART.QTY) ELSE PART.DISCOUNTUNITPRICE END ),0) AS PARTAMT
        FROM
            T_SVC_RO_OP_PART PART
        WHERE PART.ROID = ROM.ROID AND PART.STATUS != 'C')+ (SELECT COALESCE(SUM(OP.DISCOUNTBPRICE),0) AS OPAMT
        FROM T_SVC_RO_OP OP
        WHERE OP.ROID =
ROM.ROID AND OP.STATUS != 'C')) AS SUBTOTAL
    FROM T_SVC_RO_MSTR ROM INNER JOIN T_VEH_MVARIANT VEHVAR ON ROM.MVARIANTID = VEHVAR.MVARIANTID INNER JOIN T_PI_CODE_DTL PD
        ON PD.DETAILVALUE = ROM.ROTYPE AND PD.RECSTATUS = 1 INNER JOIN T_PI_CODE_MSTR PM ON PM.HEADERCODEID = PD.HEADERCODEID AND PM.HEADERCODE = 'ROTYPE' INNER JOIN
        T_SVC_RECEPTION PRE ON PRE.SUPID = ROM.SUPID INNER JOIN T_SVC_PENVEHRMK PVR ON PVR.PRERONO = PRE.SUPNO LEFT JOIN T_SVC_ADVISOR_MSTR SAM ON ROM.SVCADVISORID =
Sam.STAFFID AND ROM.OUTLETID = SAM.OUTLETID
    WHERE 1=1 AND ROM.STATUS IN ('G','R','W','Q','D') AND ROM.OUTLETCODE = :OUTLETCODEPARAM
UNION
    SELECT OM.OUTLETID, PRE.REGNO,
        VEHVAR.MVARIANTDESC, PRE.SUPSTATUS AS STATUS, SAM.STAFFID, SAM.SVCADVISORNAME, PVR.REMARKS AS REMARKS, PRE.SUPNO AS RONO, PRE.supdate AS RODATE, PRE.ARRTIME AS
ARRIVALDATE, TRUNC(SYSDATE) - TRUNC(PRE.ARRTIME) AS PENDINGDAYS, 0 AS PENDINGRODAYS, PD.DETAILDESCRIPTION AS ROTYPE, 0 AS SUBTOTAL
    FROM T_SVC_RECEPTION PRE INNER
        JOIN T_VEHCUSTPROFILE VCP ON PRE.VCPROFILEID = VCP.VCPROFILEID INNER JOIN T_VEH_MVARIANT VEHVAR ON VCP.DSSMVARIANTID = VEHVAR.MVARIANTID INNER JOIN T_PI_CODE_DTL PD
        ON PD.DETAILVALUE = PRE.ROTYPE AND PD.RECSTATUS = 1 INNER JOIN T_PI_CODE_MSTR PM ON PM.HEADERCODEID = PD.HEADERCODEID AND PM.HEADERCODE = 'ROTYPE' INNER JOIN
        T_SVC_PENVEHRMK PVR ON PVR.PRERONO = PRE.SUPNO INNER JOIN T_OUTLET_MSTR OM ON OM.OUTLETCODE = PRE.OUTLETCODE AND OM.RECSTATUS = 1 LEFT JOIN T_SVC_ADVISOR_MSTR
SAM ON PRE.SVCADVISORID = Sam.STAFFID AND PRE.OUTLETCODE = SAM.OUTLETCODE
    WHERE 1=1 AND PRE.SUPSTATUS = 'N' AND PRE.OUTLETCODE = :OUTLETCODEPARAM