CREATE OR REPLACE FORCE VIEW "DSS"."VW_PENPARTCOLCRORPT" ("OUTLETID", "OUTLETCODE", "OUTLETNAME", "CRODATE", "STATUS", "COST", "RETAIL") AS 
    SELECT MSTR.OUTLETID,MSTR.OUTLETCODE,OT.OUTLETNAME,MSTR.CRODATE,MSTR.STATUS,
    --  (CASE WHEN OT.OUTLETTYPE = 'DEALER' 
    --  THEN COALESCE(DB.AVGPARTCOST,0)
    --  ELSE COALESCE(DB.POIS_COSTPRICE,0)
    --  END) AS COST,
    DTL.TOTALAVGCOST AS COST,
    COALESCE(DTL.TOTALBASEPRICEWGST,0) AS RETAIL
    FROM T_PI_CRO_MSTR MSTR
    INNER JOIN T_OUTLET_MSTR OT ON OT.OUTLETID=MSTR.OUTLETID
    INNER JOIN T_PI_CRO_DTL DTL ON DTL.CROID=MSTR.CROID AND DTL.RECSTATUS = 1
    INNER JOIN T_PI_PART_DEFAULT_BIN DB ON DB.OUTLETID = MSTR.OUTLETID AND DB.PARTID = DTL.PARTID