SELECT DISTINCT OUTLET.OUTLETID, OUTLET.OUTLETCODE, OUTLET.OUTLETNAME AS OUTLETNAME, DC.PARTNO, DC.PARTDESC, DC.DEFAULTBIN, LISTAGG(DC.BINLOCATION,',') WITHIN GROUP (ORDER BY DC.BINLOCATION) BINLOC, DC.UOMCODE, DC.PARTTYPE, DC.OPENINGCOST, (NVL(DC.COST,0)/DC.CFACTOR) AS COSTVALUE, DC.RETAILPRICE, DC.MAD, DC.ADJMIP, DC.MIP, DC.QUANTITY AS CLOSINGSTOCK, DC.WAC AS AVERAGECOST, (DC.QUANTITY-QTYALLOCATED) AS AVAILQTY, DC.ONORDERQTY, DC.BACKORDERQTY,
    DC.CFACTOR, DC.LASTRECEIVEDDATE, DC.LASTISSUEDDATE, DC.LASTORDERDATE, NVL(DC.TOTALTRANSWAC,0) AS TOTALTRANSCOST
FROM T_DAILY_CLOSING DC INNER JOIN T_OUTLET_MSTR OUTLET ON DC.OUTLETCODE = OUTLET.OUTLETCODE
WHERE 1=1 AND (EXISTS(SELECT PMV.PARTID
    FROM T_PI_PART_MOVEMENT PMV
    WHERE PMV.OUTLETID = OUTLET.OUTLETID AND PMV.PARTID = DC.PARTID AND ROWNUM =1) OR DC.QUANTITY > 0) AND OUTLET.OUTLETCODE = :PARAMOUTLETCODE AND DC.CLOSINGDATE >= TO_DATE('07/12/2020','dd/mm/
yyyy') AND DC.CLOSINGDATE < TO_DATE('07/12/2020','dd/mm/yyyy') + 1
GROUP BY OUTLET.OUTLETID, OUTLET.OUTLETCODE, OUTLET.OUTLETNAME,DC.PARTNO, DC.PARTDESC, DC.DEFAULTBIN, DC.UOMCODE, DC.PARTTYPE, DC.OPENINGCOST, DC.COST, DC.RETAILPRICE, DC.MAD, DC.ADJMIP, DC.MIP, DC.QUANTITY, DC.WAC, (DC.QUANTITY-QTYALLOCATED), DC.ONORDERQTY, DC.BACKORDERQTY, DC.CFACTOR, DC.LASTRECEIVEDDATE, DC.LASTISSUEDDATE, DC.LASTORDERDATE,DC.TOTALTRANSWAC
ORDER BY OUTLET.OUTLETCODE,
DC.PARTNO