SELECT ROMSTR.OUTLETCODE, 
OT.OUTLETNAME, 
WTYMSTR.ROINVNO, 
ROMSTR.RONO, 
ROMSTR.SVCADVISORID, 
ADV.SVCADVISORNAME, 
TO_CHAR(ROINV.ROINVDATE, 'DD/MM/YYYY') AS ROINVDATE, 
ROMSTR.REGNO, 
ROMSTR.CHASSISNO, 
ROMSTR.ENGINENO,
    CODEDTL.DETAILDESCRIPTION AS WTYTYPE, 
	OP.OPCODE, 
	NVL(( SELECT SUM(OPDTL.FINALPRICEWGST)
    FROM T_SVC_RO_OP OPDTL
    WHERE OPDTL.WTYINCID = OP.WTYINCID AND OPDTL.OPCODE = OP.OPCODE AND SUBLETFLAG IS NULL ),0) AS SVCAMT, 
	NVL(( SELECT
        SUM(OPDTL.FINALPRICEWGST)
    FROM T_SVC_RO_OP OPDTL
    WHERE OPDTL.WTYINCID = OP.WTYINCID AND OPDTL.OPCODE = OP.OPCODE AND SUBLETFLAG = 'Y' ),0) AS SUBLETAMT, 
	NVL(( SELECT SUM(OPPART.TOTALPRICEWGST)
    FROM T_SVC_RO_OP_PART OPPART
    WHERE
OPPART.WTYINCID = OP.WTYINCID AND OPPART.OPCODE = OP.OPCODE ), 0) AS PARTAMT, 
WTYMSTR.WCFNO, TO_CHAR(WTYMSTR.CREATEDDATETIME,'DD/MM/YYYY') AS WCFDATE, 
WTYMSTR.STATUS, REGION.REGIONDESC, TRUNC(CURRENT_DATE) - TRUNC(ROINV.ROINVDATE) AS AGING, 
TO_CHAR(CURRENT_DATE, 'DD/MM/YYYY') AS DATEGEN

FROM T_SVC_WCF_MSTR WTYMSTR INNER JOIN T_SVC_RO_WTYINC_MSTR INCMSTR ON WTYMSTR.WTYINCID = INCMSTR.WTYINCID 
							INNER JOIN T_SVC_RO_OP OP ON INCMSTR.WTYINCID = OP.WTYINCID 
							INNER JOIN T_SVC_RO_MSTR ROMSTR ON WTYMSTR.ROID = ROMSTR.ROID 
							INNER JOIN T_SVC_RO_INV_MSTR ROINV ON ROINV.ROINVID = WTYMSTR.ROINVID 
							INNER JOIN T_OUTLET_MSTR OT ON ROMSTR.OUTLETID = OT.OUTLETID 
							INNER JOIN T_REGION_MSTR REGION ON OT.REGIONID =REGION.REGIONID 
							INNER JOIN T_SVC_ADVISOR_MSTR ADV ON ADV.STAFFID = ROMSTR.SVCADVISORID AND ADV.STATUS = 'A' AND ADV.OUTLETID = ROMSTR.OUTLETID 
							INNER JOIN T_PI_CODE_DTL CODEDTL ON INCMSTR.WTYTYPE = CODEDTL.DETAILVALUE 
							INNER JOINT_PI_CODE_MSTR CODEMSTR ON CODEMSTR.HEADERCODEID = CODEDTL.HEADERCODEID AND CODEMSTR.HEADERCODE = 'WTYTYPE'
WHERE 1=1 AND OT.OUTLETCODE = :PARAMOUTLETCODE AND ROINV.ROINVDATE >= TO_DATE('01/12/2020', 'DD/MM/YYYY') AND ROINV.ROINVDATE <=
TO_DATE('31/12/2020', 'DD/MM/YYYY') + 1