SELECT OUTLETCODE, RONO, ROINVDATE, CURRMILEAGE, ROINVNO, REGNO, REGDATE, APPTBKNO, MFAMILYCODE, CUST_TYPE_DESC, ROSTATUS, CUSTNO, CUSTNAME, SVCADVISORNAME, SUM(LABOUR) AS LABOUR, SUM(PARTPARTS) AS PARTPARTS, SUM(PARTACC) AS PARTACC, SUM(PARTLUB) AS PARTLUB, SUM(PARTMTL) AS PARTMTL, SUM(PARTLUBESUB) AS PARTLUBESUB, COALESCE(SUM(DISCLABOUR),0) AS
DISCLABOUR, COALESCE(SUM(DISCPARTS),0) AS DISCPARTS, COALESCE(SUM(DISCACC),0) AS DISCACC, COALESCE(SUM(DISCLUB),0) AS DISCLUB, COALESCE(SUM(DISCMTL),0) AS DISCMTL, SUM(DISCCASH) AS DISCCASH, COALESCE(SUM(CAMPDISCLBAMT+CAMPDISCPARTAMT),0) AS CAMPDISC, COALESCE(SUM(PKGOPDISCAMT+PKGPARTDISCAMT),0) AS PCKGDISC, SUM(RETURNJOBLOST) AS RETURNJOBLOST, SUM(EXCESS) AS
EXCESS, SUM(ROUNDINGADJAMOUNT) AS ROUNDINGADJAMOUNT, SUM(TOTALAMOUNT) AS TOTALAMOUNT, SUM(PAIDAMOUNT) AS PAIDAMOUNT, SUM(CASHCOLL) AS CASHCOLL, SUM(CREDITCOLL) AS CREDITCOLL, SUM(CREDITCARDCOLL) AS CREDITCARDCOLL, SUM(CASHDEPOSIT) AS CASHDEPOSIT, SUM(CCDEPOSIT) AS CCDEPOSIT, SUM(TAX) AS TAX, SUM(WTYTAX) AS WTYTAX, SUM(COSTLABOUR) AS COSTLABOUR,
    SUM(COSTSUBLET) AS COSTSUBLET, SUM(COSTMAT) AS COSTMAT, SUM(COSTPARTS) AS COSTPARTS, SUM(COSTACC) AS COSTACC, SUM(COSTLUB) AS COSTLUB
	
FROM ( SELECT RO.OUTLETCODE, RO.RONO, IM.ROINVDATE, RO.CURRMILEAGE, IM.ROINVNO, RO.REGNO, RO.REGDATE, RO.APPTBKNO, CP.CUSTNO, CP.CUSTNAME, 
(SELECT VF.MFAMILYCODE
        FROM T_VEHCUSTPROFILE TVCP, T_VEH_MVARIANT MV, T_VEH_MFAMILY VF
        WHERE TVCP.VCPROFILEID = VCP.VCPROFILEID AND VCP.DSSMVARIANTID = MV.MVARIANTID AND MV.MFAMILYID = VF.MFAMILYID) AS MFAMILYCODE, 
		(SELECT AM.SVCADVISORNAME  FROM T_SVC_ADVISOR_MSTR AM
        WHERE AM.STAFFID = RO.SVCADVISORID AND AM.OUTLETID = RO.OUTLETID) AS SVCADVISORNAME, 
		(SELECT CUSTGRP.CUSTGROUPDESC FROM t_custgroup_mstr CUSTGRP WHERE CP.CUSTGRP = CUSTGRP.CUSTGROUPCODE) AS CUST_TYPE_DESC, 
		CASE WHEN RO.STATUS = 'I' THEN 'INVOICED' WHEN RO.STATUS = 'P' THEN 'PAYMENT RECEIVED' ELSE RO.STATUS END AS ROSTATUS,
		(SELECT COALESCE(SUM(RIO.FINALPRICEWOGST),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN
            T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_OP RIO ON RIM.ROINVID = RIO.ROINVID
        WHERE RIO.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND ROP.ROOPID=RIO.ROOPID) AS LABOUR,
		(SELECT COALESCE(SUM(RIP.TOTALPRICEWOGST),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART
ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID AND RIP.ROOPPARTID = ROP.ROOPPARTID AND RIP.CHARGETYPECODE = 'SO-W' INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID =
PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID AND UPPER(PTM.PARTTYPECODE) = 'PARTS'
        WHERE RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID) AS PARTPARTS, (SELECT COALESCE(SUM(RIP.TOTALPRICEWOGST),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID =
WIM.WTYINCID AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID AND RIP.ROOPPARTID = ROP.ROOPPARTID AND RIP.CHARGETYPECODE = 'SO-W' INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID AND
                UPPER(PTM.PARTTYPECODE) = 'ACCESSORIES'
        WHERE RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID) AS PARTACC, (SELECT COALESCE(SUM(RIP.TOTALPRICEWOGST),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' INNER JOIN
            T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID AND RIP.ROOPPARTID = ROP.ROOPPARTID AND RIP.CHARGETYPECODE = 'SO-W' INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID AND UPPER(PTM.PARTTYPECODE) IN ('OIL & LUBRICANT')
        WHERE RIM.ROINVID =
IM.ROINVID AND SRM.ROID = RO.ROID) AS PARTLUB, (SELECT COALESCE(SUM(RIP.TOTALPRICEWOGST),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP
            ON RIM.ROINVID = RIP.ROINVID AND RIP.ROOPPARTID = ROP.ROOPPARTID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID AND RIP.CHARGETYPECODE = 'SO-W' INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID AND UPPER(PTM.PARTTYPECODE) IN ('LUBE SUB PRODUCT')
        WHERE RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID) AS PARTLUBESUB, (SELECT
            COALESCE(SUM(RIP.TOTALPRICEWOGST),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID AND RIP.ROOPPARTID =
ROP.ROOPPARTID AND RIP.CHARGETYPECODE = 'SO-W' INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID AND UPPER(PTM.PARTTYPECODE) = 'MTL'
        WHERE RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID) AS PARTMTL, (SELECT CASE WHEN COALESCE(SUM(RIO.DISCOUNT),0) IS NOT NULL AND COALESCE(SUM(RIO.DISCOUNT),0) != 0
THEN COALESCE(SUM(RIO.DISCOUNT),0) END
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_OP RIO ON RIM.ROINVID = RIO.ROINVID
        WHERE RIO.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS
= 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND ROP.ROOPID=RIO.ROOPID) AS DISCLABOUR , ( SELECT CASE WHEN COALESCE(SUM(RIP.DISCOUNT),0) IS NOT NULL AND COALESCE(SUM(RIP.DISCOUNT),0) != 0 THEN COALESCE(SUM(RIP.DISCOUNT*RIP.QTY),0) END
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON
ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) = 'PARTS' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND
            WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND RIP.ROOPPARTID=ROP.ROOPPARTID) AS DISCPARTS , ( SELECT CASE WHEN COALESCE(SUM(RIP.DISCOUNT),0) IS NOT NULL AND COALESCE(SUM(RIP.DISCOUNT),0) != 0 THEN COALESCE(SUM(RIP.DISCOUNT*RIP.QTY),0) END
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN
            T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) = 'ACCESSORIES' AND RIP.CHARGETYPECODE
= 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND RIP.ROOPPARTID=ROP.ROOPPARTID) AS DISCACC , ( SELECT CASE WHEN COALESCE(SUM(RIP.DISCOUNT),0) IS NOT NULL AND COALESCE(SUM(RIP.DISCOUNT),0) != 0 THEN COALESCE(SUM(RIP.DISCOUNT*RIP.QTY),0) END
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID =
ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) IN ( 'OIL &
LUBRICANT','LUBE SUB PRODUCT') AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND RIP.ROOPPARTID=ROP.ROOPPARTID) AS DISCLUB, ( SELECT CASE WHEN COALESCE(SUM(RIP.DISCOUNT),0) IS NOT NULL AND COALESCE(SUM(RIP.DISCOUNT),0) != 0 THEN COALESCE(SUM(RIP.DISCOUNT*RIP.QTY),0) END
        FROM
            T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID =
PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) = 'MTL' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND RIP.ROOPPARTID=ROP.ROOPPARTID) AS DISCMTL, (SELECT COALESCE(SUM(RIM.GSTTAXAMOUNT),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID
        WHERE
RIM.ROINVTYPECODE = 'SOFLEKSIB' AND RIM.ROINVID = IM.ROINVID ) AS TAX, (SELECT COALESCE(SUM(RIM.GSTTAXAMOUNT),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID
        WHERE RIM.ROINVTYPECODE = 'SOW' AND RIM.ROINVID = IM.ROINVID ) AS WTYTAX, (SELECT COALESCE(SUM(SRM.TOTALAMOUNT),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_INV_MSTR RIM ON
RIM.ROID = SRM.ROID
        WHERE SRM.ROTYPE = 'CBJ' AND RIM.ROINVID = IM.ROINVID ) AS RETURNJOBLOST, 0 AS DISCCASH, COALESCE(RO.CAMPDISCLBAMT,0) AS CAMPDISCLBAMT, COALESCE(RO.CAMPDISCPARTAMT,0) AS CAMPDISCPARTAMT, COALESCE(RO.PKGOPDISCAMT,0) AS PKGOPDISCAMT, COALESCE(RO.PKGPARTDISCAMT,0) AS PKGPARTDISCAMT, COALESCE(IM.TAXAMOUNT,0) AS TAXAMOUNT,
        COALESCE(IM.INSEXCESSAMT,0) AS EXCESS, COALESCE(IM.ROUNDINGADJAMOUNT,0) AS ROUNDINGADJAMOUNT, COALESCE(IM.TOTALAMOUNT,0) AS TOTALAMOUNT, COALESCE(IM.PAIDAMOUNT,0) AS PAIDAMOUNT, (SELECT COALESCE(SUM(PD.PMTAMT),0)
        FROM T_SVC_PMTRECEIPT_MSTR PM INNER JOIN T_SVC_PMTRECEIPT_DTL PD ON PM.PRID = PD.PRID AND PD.PAYMODECODE = 'CASH' INNER JOIN
            T_SVC_PMTRECEIPT_DTL_INFO PDI ON PM.PRID = PDI.PRID AND PDI.DOCTYPE = 'INVOICE' INNER JOIN T_SVC_RO_INV_MSTR RIM ON PDI.DOCNO = RIM.ROINVNO
        WHERE PM.PAYTYPECODE = 'NOR' AND RIM.ROINVID = IM.ROINVID ) AS CASHCOLL, (SELECT COALESCE(SUM(PD.PMTAMT),0)
        FROM T_SVC_PMTRECEIPT_MSTR PM INNER JOIN T_SVC_PMTRECEIPT_DTL PD ON PM.PRID = PD.PRID INNER JOIN T_SVC_PMTRECEIPT_DTL_INFO
PDI ON PM.PRID = PDI.PRID AND PDI.DOCTYPE = 'INVOICE' INNER JOIN T_SVC_RO_INV_MSTR RIM ON PDI.DOCNO = RIM.ROINVNO INNER JOIN T_CUSTPROFILE CP ON PM.CUSTPROFILEID = CP.CUSTPROFILEID AND CP.PAYMENTTYPE = 'D'
        WHERE RIM.ROINVID = IM.ROINVID) AS CREDITCOLL, (SELECT COALESCE(SUM(PD.PMTAMT),0)
        FROM T_SVC_PMTRECEIPT_MSTR PM INNER JOIN T_SVC_PMTRECEIPT_DTL PD ON PM.PRID = PD.PRID
                AND PD.PAYMODECODE = 'CREDITCARD' INNER JOIN T_SVC_PMTRECEIPT_DTL_INFO PDI ON PM.PRID = PDI.PRID AND PDI.DOCTYPE = 'INVOICE' INNER JOIN T_SVC_RO_INV_MSTR RIM ON PDI.DOCNO = RIM.ROINVNO
        WHERE PM.PAYTYPECODE = 'NOR' AND RIM.ROINVID = IM.ROINVID) AS CREDITCARDCOLL, (SELECT COALESCE(SUM(PD.PMTAMT),0)
        FROM T_SVC_PMTRECEIPT_MSTR PM INNER JOIN T_SVC_PMTRECEIPT_DTL PD ON
PM.PRID = PD.PRID AND PD.PAYMODECODE = 'CASH' INNER JOIN T_SVC_PMTRECEIPT_DTL_INFO PDI ON PM.PRID = PDI.PRID AND PDI.DOCTYPE = 'INVOICE' INNER JOIN T_SVC_RO_INV_MSTR RIM ON PDI.DOCNO = RIM.ROINVNO
        WHERE PM.PAYTYPECODE = 'DEP' AND RIM.ROINVID = IM.ROINVID) AS CASHDEPOSIT, (SELECT COALESCE(SUM(PD.PMTAMT),0)
        FROM T_SVC_PMTRECEIPT_MSTR PM INNER JOIN T_SVC_PMTRECEIPT_DTL PD
            ON PM.PRID = PD.PRID AND PD.PAYMODECODE = 'CREDITCARD' INNER JOIN T_SVC_PMTRECEIPT_DTL_INFO PDI ON PM.PRID = PDI.PRID AND PDI.DOCTYPE = 'INVOICE' INNER JOIN T_SVC_RO_INV_MSTR RIM ON PDI.DOCNO = RIM.ROINVNO
        WHERE PM.PAYTYPECODE = 'DEP' AND RIM.ROINVID = IM.ROINVID) AS CCDEPOSIT, 0 AS COSTLABOUR, ( nvl((SELECT SUM(nvl(sj.TOTALAMTWOGST,0)) AS TotalSubeletJobCost
        FROM
            T_SVC_SUBLET_WO_MSTR sw INNER JOIN t_svc_sublet_wo_op sj ON sw.subletwoid = sj.subletwoid INNER JOIN t_svc_ro_op rop ON sj.roopid = rop.roopid INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID
        WHERE sw.status != 'C' AND rop.subletcode is not null AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND rop.recstatus = 1 AND rop.status != 'C' AND REPLACE(rop.chargetypecode,'-','') = IM.ROINVTYPECODE AND
            rop.roid = RO.ROID) ,0) + nvl(( SELECT SUM(nvl(sp.TOTALAMTWOGST,0)) AS TotalSubeletPartCost
        FROM T_SVC_SUBLET_WO_MSTR sw INNER JOIN t_svc_sublet_wo_part sp ON sw.subletwoid = sp.subletwoid INNER JOIN t_svc_ro_op_part ropp ON sp.rooppartid = ropp.rooppartid INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROPp.WTYINCID = WIM.WTYINCID
        WHERE sw.status != 'C' AND ropp.recstatus = 1 AND ropp.status != 'C' AND WIM.WTYTYPE
= 'WTY' AND WIM.STATUS = 'N' AND REPLACE(ropp.chargetypecode,'-','') = IM.ROINVTYPECODE AND ropp.roid = RO.ROID) ,0) ) AS COSTSUBLET, ( SELECT NVL(SUM(COALESCE(RIP.UNITAVGCOST,0)),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID =
SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) = 'MTL' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND
            RIP.ROOPPARTID=ROP.ROOPPARTID ) - (select COALESCE(sum(RIP.UNITAVGCOST),0)
        from T_PI_PART_MSTR PM INNER JOIN T_PI_PARTTYPE_MSTR PTM ON pm.parttypeid = ptm.parttypeid INNER JOIN T_svc_ro_op_part ropp ON ropp.partid = pm.partid and ropp.recstatus = 1 and ropp.status != 'C' INNER JOIN T_svc_sublet_wo_part sp ON sp.rooppartid = ropp.rooppartid and sp.suggestedamount > 0 INNER JOIN T_SVC_SUBLET_WO_MSTR sw ON
sw.subletwoid = sp.subletwoid and sw.status != 'C' INNER JOIN T_PI_PART_DEFAULT_BIN PBIN ON ropp.PARTID = PBIN.PARTID INNER JOIN T_SVC_RO_INV_PART RIP ON RIP.ROOPPARTID = ropp.ROOPPARTID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROPp.WTYINCID = WIM.WTYINCID
        where UPPER(PTM.PARTTYPECODE) = 'MTL' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND IM.ROID =
RO.ROID and ropp.roid = RO.ROID AND RIP.ROINVID = IM.ROINVID AND RO.OUTLETID = PBIN.OUTLETID ) AS COSTMAT, ( SELECT NVL(SUM(COALESCE(RIP.UNITAVGCOST,0)),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN
            T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) = 'PARTS' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND
            RIP.ROOPPARTID=ROP.ROOPPARTID ) - (select COALESCE(sum(RIP.UNITAVGCOST),0)
        from T_PI_PART_MSTR PM INNER JOIN T_PI_PARTTYPE_MSTR PTM ON pm.parttypeid = ptm.parttypeid INNER JOIN T_svc_ro_op_part ropp ON ropp.partid = pm.partid and ropp.recstatus = 1 and ropp.status != 'C' INNER JOIN T_svc_sublet_wo_part sp ON sp.rooppartid = ropp.rooppartid and sp.suggestedamount > 0 INNER JOIN T_SVC_SUBLET_WO_MSTR sw ON
sw.subletwoid = sp.subletwoid and sw.status != 'C' INNER JOIN T_PI_PART_DEFAULT_BIN PBIN ON ropp.PARTID = PBIN.PARTID INNER JOIN T_SVC_RO_INV_PART RIP ON RIP.ROOPPARTID = ropp.ROOPPARTID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROPp.WTYINCID = WIM.WTYINCID
        where UPPER(PTM.PARTTYPECODE) = 'PARTS' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND
            IM.ROID = RO.ROID and ropp.roid = RO.ROID AND RIP.ROINVID = IM.ROINVID AND RO.OUTLETID = PBIN.OUTLETID ) AS COSTPARTS, ( SELECT NVL(SUM(COALESCE(RIP.UNITAVGCOST,0)),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID
            INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) = 'ACCESSORIES' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND
            RIP.ROOPPARTID=ROP.ROOPPARTID ) - (select COALESCE(sum(RIP.UNITAVGCOST),0)
        from T_PI_PART_MSTR PM INNER JOIN T_PI_PARTTYPE_MSTR PTM ON pm.parttypeid = ptm.parttypeid INNER JOIN T_svc_ro_op_part ropp ON ropp.partid = pm.partid and ropp.recstatus = 1 and ropp.status != 'C' INNER JOIN T_svc_sublet_wo_part sp ON sp.rooppartid = ropp.rooppartid and sp.suggestedamount > 0 INNER JOIN T_SVC_SUBLET_WO_MSTR sw ON
sw.subletwoid = sp.subletwoid and sw.status != 'C' INNER JOIN T_PI_PART_DEFAULT_BIN PBIN ON ropp.PARTID = PBIN.PARTID INNER JOIN T_SVC_RO_INV_PART RIP ON RIP.ROOPPARTID = ropp.ROOPPARTID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROPp.WTYINCID = WIM.WTYINCID
        where UPPER(PTM.PARTTYPECODE) = 'ACCESSORIES' AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND
            IM.ROID = RO.ROID and ropp.roid = RO.ROID AND RIP.ROINVID = IM.ROINVID AND RO.OUTLETID = PBIN.OUTLETID ) AS COSTACC, ( SELECT NVL(SUM(COALESCE(RIP.UNITAVGCOST,0)),0)
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER
            JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE UPPER(PTM.PARTTYPECODE) IN ( 'OIL & LUBRICANT','LUBE SUB PRODUCT') AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE = 'WTY' AND WIM.STATUS = 'N' AND RIM.ROINVID = IM.ROINVID AND SRM.ROID =
RO.ROID AND RIP.ROOPPARTID=ROP.ROOPPARTID ) - (select COALESCE(sum(RIP.UNITAVGCOST),0)
        from T_PI_PART_MSTR PM INNER JOIN T_PI_PARTTYPE_MSTR PTM ON pm.parttypeid = ptm.parttypeid INNER JOIN T_svc_ro_op_part ropp ON ropp.partid = pm.partid and ropp.recstatus = 1 and ropp.status != 'C' INNER JOIN T_svc_sublet_wo_part sp ON sp.rooppartid = ropp.rooppartid and sp.suggestedamount > 0 INNER JOIN T_SVC_SUBLET_WO_MSTR
sw ON sw.subletwoid = sp.subletwoid and sw.status != 'C' INNER JOIN T_PI_PART_DEFAULT_BIN PBIN ON ropp.PARTID = PBIN.PARTID INNER JOIN T_SVC_RO_INV_PART RIP ON RIP.ROOPPARTID = ropp.ROOPPARTID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROPp.WTYINCID = WIM.WTYINCID
        where UPPER(PTM.PARTTYPECODE) IN ( 'OIL & LUBRICANT','LUBE SUB PRODUCT') AND RIP.CHARGETYPECODE = 'SO-W' AND WIM.WTYTYPE =
'WTY' AND WIM.STATUS = 'N' AND IM.ROID = RO.ROID and ropp.roid = RO.ROID AND RIP.ROINVID = IM.ROINVID AND RO.OUTLETID = PBIN.OUTLETID ) AS COSTLUB
    FROM T_SVC_RO_INV_MSTR IM INNER JOIN T_SVC_RO_MSTR RO ON IM.ROID = RO.ROID INNER JOIN T_CUSTPROFILE CP ON RO.CUSTPROFILEID = CP.CUSTPROFILEID INNER JOIN T_VEHCUSTPROFILE VCP ON RO.VCPROFILEID = VCP.VCPROFILEID AND VCP.CUSTPROFILEID= CP.CUSTPROFILEID
    WHERE (IM.ROINVID IN (SELECT DISTINCT RIO.ROINVID
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP ROP ON SRM.ROID = ROP.ROID INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID AND WIM.WTYTYPE IN ('WTY') INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_OP RIO ON RIM.ROINVID = RIO.ROINVID AND
                RIO.CHARGETYPECODE = 'SO-W'
        WHERE RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND RIM.STATUS NOT IN ('C','S') AND SRM.OUTLETCODE = :PARAMOUTLETCODE AND RIM.ROINVDATE >= TO_DATE('01/12/2020','DD/MM/YYYY') AND RIM.ROINVDATE < TO_DATE('31/12/2020','DD/MM/YYYY') + 1 ) OR IM.ROINVID IN (SELECT DISTINCT RIP.ROINVID
        FROM T_SVC_RO_MSTR SRM INNER JOIN T_SVC_RO_OP_PART ROP ON SRM.ROID = ROP.ROID
            INNER JOIN T_SVC_RO_WTYINC_MSTR WIM ON ROP.WTYINCID = WIM.WTYINCID AND WIM.WTYTYPE IN ('WTY') INNER JOIN T_SVC_RO_INV_MSTR RIM ON RIM.ROID = SRM.ROID INNER JOIN T_SVC_RO_INV_PART RIP ON RIM.ROINVID = RIP.ROINVID AND RIP.CHARGETYPECODE = 'SO-W' INNER JOIN T_PI_PART_MSTR PM ON RIP.PARTID = PM.PARTID INNER JOIN T_PI_PARTTYPE_MSTR PTM ON PM.PARTTYPEID = PTM.PARTTYPEID
        WHERE
RIM.ROINVID = IM.ROINVID AND SRM.ROID = RO.ROID AND RIM.STATUS NOT IN ('C','S') AND SRM.OUTLETCODE = :PARAMOUTLETCODE AND RIM.ROINVDATE >= TO_DATE('01/12/2020','DD/MM/YYYY') AND RIM.ROINVDATE < TO_DATE('31/12/2020','DD/MM/YYYY') + 1 )) )
GROUP BY OUTLETCODE, RONO, ROINVDATE, CURRMILEAGE, ROINVNO, REGNO, REGDATE, APPTBKNO, MFAMILYCODE, CUST_TYPE_DESC, ROSTATUS, CUSTNO, CUSTNAME,
SVCADVISORNAME
ORDER BY OUTLETCODE, RONO, ROINVDATE, CURRMILEAGE, ROINVNO